# docker-compose.yml (For Development Environment)
# This file is configured for local development with live code reloading.
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peps_app_dev # Distinct name for the development container
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    volumes:
      # Mounts the current directory on the host to /var/www/html in the container.
      # This enables live reloading: changes made to your local code
      # will be immediately reflected in the running application.
      # The db.sqlite file will reside in ./template/functions/ on your host.
      - .:/var/www/html
    restart: unless-stopped # Or "no" if you prefer it to stay down on errors during dev
