version: '3.8' # Specifies the Docker Compose file format version

services:
  app:
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: peps_app # A friendly name for the container
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/var/www/html # Map current directory to web root in container
    restart: unless-stopped # Restart policy for the container
